class Hotstar{

		static String movies[]={"Brahmastra","Sita Ram","Atrangi Re","Viram","Cadaveer","Shiddat","Dil Bechara","Chhichhore","Mission Mangal","Arjun Reddy"};
		static String englishMovies[]={"Titanic","The Lion King","Avatar","Prey","JungleCruise","Luca","The First Omen","Frozen","Avengers","Angrezi Medium","Indian Jones","Eternals","Black Panther","Mona","Thor","Mulan","Kingsman","Ford v Ferrari","Nomadland","Free Guy","Glass","Prey","Life of Pi","The Last Duel","Hidden Figures"};
		static String kannadaMovies[]={"Kavacha","Ambi Ning Vayassaytho"," Anna Bond","Tarak","Pataki","Godhi Banna Sadharana Mykattu","Parapancha","Hudugaru","Bahaddur","Bharjari","Savaari 2","Kiccha Huccha","Porki","Mast Maja Maadi","Aptharakshaka","Gaalipata","Paramatma","Mungaru Male","Yaare kugadali","Varadanayaka","Chingari","Sagar","Drishya","Nenapirali","Chamak"};
		static String hindiMovies[]={"Chhichhore","Badhaai Ho","Super 30","Raid","Angrezi Medium","Sanju","Bajrangi Bhaijaan","Hindi Medium","Baby","Mission Mangal","Maqbool","Tanhaji","Govinda Naam Mera","Talvar","Bhaag Milkha Bhaag","Hungama 2","12th Fail","Gulmohar","A Thursday","Pink","Neerja","Stree","Kaabil","Fukrey","Jolly LLB"};
		static String koreanSeries[]={"Call it Love","Going to you at A speed of 493km","Sketch","Grid","Rookie Cops","Sixth Sense","Moving","Graceful Friends","Snowdrop","Revenge of Others","BigMouth","Crazy Love","Listen to Love","Link:Eat, love, Kill","Bloody Heart","Adamas","The Light in Your Eyes","Diary of a Prosecutor","When the Weather is Nice","More Than Friends","Soundtrack#1","Fantastic","Golden Spoon","The Package","Put your head on my shoulder"};
		
		public static void main(String entertainment[]){
		
		System.out.println("Movies are:\n"+movies[0]+"\n"+movies[1]+"\n"+movies[2]+"\n"+movies[3]+"\n"+movies[4]+"\n"+movies[5]+"\n"+movies[6]+"\n"+movies[7]+"\n"+movies[8]+"\n"+movies[9]);
		System.out.println("English Movies are:\n"+englishMovies[0]+"\n"+englishMovies[1]+"\n"+englishMovies[2]+"\n"+englishMovies[3]+"\n"+englishMovies[4]+"\n"+englishMovies[5]+"\n"+englishMovies[6]+"\n"+englishMovies[7]+"\n"+englishMovies[8]+"\n"+englishMovies[9]+"\n"+englishMovies[10]+"\n"+englishMovies[11]+"\n"+englishMovies[12]+"\n"+englishMovies[13]+"\n"+englishMovies[14]+"\n"+englishMovies[15]+"\n"+englishMovies[16]+"\n"+englishMovies[17]+"\n"+englishMovies[18]+"\n"+englishMovies[19]+"\n"+englishMovies[20]+"\n"+englishMovies[21]+"\n"+englishMovies[22]+"\n"+englishMovies[23]+"\n"+englishMovies[24]);
		System.out.println("Kannada Movies are:\n"+kannadaMovies[0]+"\n"+kannadaMovies[1]+"\n"+kannadaMovies[2]+"\n"+kannadaMovies[3]+"\n"+kannadaMovies[4]+"\n"+kannadaMovies[5]+"\n"+kannadaMovies[6]+"\n"+kannadaMovies[7]+"\n"+kannadaMovies[8]+"\n"+kannadaMovies[9]+"\n"+kannadaMovies[10]+"\n"+kannadaMovies[11]+"\n"+kannadaMovies[12]+"\n"+kannadaMovies[13]+"\n"+kannadaMovies[14]+"\n"+kannadaMovies[15]+"\n"+kannadaMovies[16]+"\n"+kannadaMovies[17]+"\n"+kannadaMovies[18]+"\n"+kannadaMovies[19]+"\n"+kannadaMovies[20]+"\n"+kannadaMovies[21]+"\n"+kannadaMovies[22]+"\n"+kannadaMovies[23]+"\n"+kannadaMovies[24]);
		System.out.println("Hindi Movies Movies are:\n"+hindiMovies[0]+"\n"+hindiMovies[1]+"\n"+hindiMovies[2]+"\n"+hindiMovies[3]+"\n"+hindiMovies[4]+"\n"+hindiMovies[5]+"\n"+hindiMovies[6]+"\n"+hindiMovies[7]+"\n"+hindiMovies[8]+"\n"+hindiMovies[9]+"\n"+hindiMovies[10]+"\n"+hindiMovies[11]+"\n"+hindiMovies[12]+"\n"+hindiMovies[13]+"\n"+hindiMovies[14]+"\n"+hindiMovies[15]+"\n"+hindiMovies[16]+"\n"+hindiMovies[17]+"\n"+hindiMovies[18]+"\n"+hindiMovies[19]+"\n"+hindiMovies[20]+"\n"+hindiMovies[21]+"\n"+hindiMovies[22]+"\n"+hindiMovies[23]+"\n"+hindiMovies[24]);
		System.out.println("Korean Series are:\n"+koreanSeries[0]+"\n"+koreanSeries[1]+"\n"+koreanSeries[2]+"\n"+koreanSeries[3]+"\n"+koreanSeries[4]+"\n"+koreanSeries[5]+"\n"+koreanSeries[6]+"\n"+koreanSeries[7]+"\n"+koreanSeries[8]+"\n"+koreanSeries[9]+"\n"+koreanSeries[10]+"\n"+koreanSeries[11]+"\n"+koreanSeries[12]+"\n"+koreanSeries[13]+"\n"+koreanSeries[14]+"\n"+koreanSeries[15]+"\n"+koreanSeries[16]+"\n"+koreanSeries[17]+"\n"+koreanSeries[18]+"\n"+koreanSeries[19]+"\n"+koreanSeries[20]+"\n"+koreanSeries[21]+"\n"+koreanSeries[22]+"\n"+koreanSeries[23]+"\n"+koreanSeries[24]);
		}
		}